---
abstract: 'Simple class modelling Calendars'
author:
  - 'Aaron Trevena <teejay@cpan.org>'
build_requires:
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Calendar-Model
no_index:
  directory:
    - t
    - inc
requires:
  Calendar::List: 0.26
  Date::Holidays: 0.15
  DateTime: 0
  I18N::Langinfo: 0
  Moose: 2
  MooseX::Role::Pluggable: 0.02
  perl: 5.006
resources:
  repository: https://github.com/hashbangperl/perl-calendar-model
version: 0.04
